"""empty message

Revision ID: b19ef2853c36
Revises: d333f8722dc3
Create Date: 2026-07-16 02:01:39.065326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19ef2853c36'
down_revision: Union[str, Sequence[str], None] = 'd333f8722dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_applications', sa.Column('description', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles_applications', 'description')
    # ### end Alembic commands ###
